[2025-04-21T16:54:18.791+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-21T16:54:18.798+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl.load_to_postgres manual__2025-04-21T07:00:36.233762+00:00 [queued]>
[2025-04-21T16:54:18.801+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl.load_to_postgres manual__2025-04-21T07:00:36.233762+00:00 [queued]>
[2025-04-21T16:54:18.801+0800] {taskinstance.py:2867} INFO - Starting attempt 11 of 11
[2025-04-21T16:54:18.806+0800] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-04-21 07:00:36.233762+00:00
[2025-04-21T16:54:18.810+0800] {standard_task_runner.py:72} INFO - Started process 21986 to run task
[2025-04-21T16:54:18.814+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_etl', 'load_to_postgres', 'manual__2025-04-21T07:00:36.233762+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_dag.py', '--cfg-path', '/var/folders/mz/6xjq0zld5fj5_cth7lsfpxlr0000gp/T/tmpk5j2z69t']
[2025-04-21T16:54:18.815+0800] {standard_task_runner.py:105} INFO - Job 40: Subtask load_to_postgres
[2025-04-21T16:54:18.835+0800] {task_command.py:467} INFO - Running <TaskInstance: weather_etl.load_to_postgres manual__2025-04-21T07:00:36.233762+00:00 [running]> on host luiss-mbp.realtek
[2025-04-21T16:54:18.864+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='weather_etl' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-21T07:00:36.233762+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-21T07:00:36.233762+00:00'
[2025-04-21T16:54:18.865+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-21T16:54:18.865+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-21T16:54:18.865+0800] {logging_mixin.py:190} INFO - Current task name:load_to_postgres state:running start_date:2025-04-21 08:54:18.798325+00:00
[2025-04-21T16:54:18.865+0800] {logging_mixin.py:190} INFO - Dag name:weather_etl and current dag run status:running
[2025-04-21T16:54:18.865+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-21T16:54:18.867+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/luisl/airflow/dags/weather_etl_dag.py", line 91, in load_to_postgres
    df=pd.read_csv("/Users/luisl/OneDrive/Documents/LUIS/Project/YourProjectName/DEPath2/weather_etl/data/cleaned_weather.csv")
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luisl/OneDrive/Documents/LUIS/Project/YourProjectName/DEPath2/weather_etl/data/cleaned_weather.csv'
[2025-04-21T16:54:18.892+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-21T16:54:18.892+0800] {logging_mixin.py:190} INFO - Task start:2025-04-21 08:54:18.798325+00:00 end:2025-04-21 08:54:18.892091+00:00 duration:0.093766
[2025-04-21T16:54:18.892+0800] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_to_postgres> dag:<DAG: weather_etl> dagrun:<DagRun weather_etl @ 2025-04-21 07:00:36.233762+00:00: manual__2025-04-21T07:00:36.233762+00:00, state:running, queued_at: 2025-04-21 08:54:13.880025+00:00. externally triggered: True>
[2025-04-21T16:54:18.892+0800] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/Users/luisl/OneDrive/Documents/LUIS/Project/YourProjectName/DEPath2/weather_etl/data/cleaned_weather.csv'
[2025-04-21T16:54:18.893+0800] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=weather_etl, task_id=load_to_postgres, run_id=manual__2025-04-21T07:00:36.233762+00:00, execution_date=20250421T070036, start_date=20250421T085418, end_date=20250421T085418
[2025-04-21T16:54:18.899+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-21T16:54:18.899+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 40 for task load_to_postgres ([Errno 2] No such file or directory: '/Users/luisl/OneDrive/Documents/LUIS/Project/YourProjectName/DEPath2/weather_etl/data/cleaned_weather.csv'; 21986)
Traceback (most recent call last):
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/luisl/airflow/dags/weather_etl_dag.py", line 91, in load_to_postgres
    df=pd.read_csv("/Users/luisl/OneDrive/Documents/LUIS/Project/YourProjectName/DEPath2/weather_etl/data/cleaned_weather.csv")
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/Users/luisl/Library/Python/3.9/lib/python/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luisl/OneDrive/Documents/LUIS/Project/YourProjectName/DEPath2/weather_etl/data/cleaned_weather.csv'
[2025-04-21T16:54:18.907+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-21T16:54:18.913+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-21T16:54:18.913+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
